[package]
name = "rxx"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0"

[build-dependencies]
rxxgen = { path = "rxxgen"}
cc = "1.0.73"
anyhow = "1.0.58"
handlebars = "4.3"
serde_json = "1.0"

[workspace]
members = ["rxxgen"]

[features]
test = []